export const countries = [
  { country: "US" },
  { country: "gb" },
  { country: "ca" },
  { country: "cn" },
  { country: "hr" },
  { country: "nl" },
  { country: "eg" },
  { country: "ph" },
  { country: "fr" },
  { country: "gr" },
  { country: "in" },
  { country: "ie" },
  { country: "it" },
  { country: "jm" },
  { country: "jp" },
  { country: "my" },
  { country: "mx" },
  { country: "ma" },
  { country: "pl" },
  { country: "pt" },
  { country: "ru" },
  { country: "es" },
  { country: "th" },
  { country: "tn" },
  { country: "tr" },
  { country: "vn" }
];
